dist: precise
language: python
python:
  - "3.6"

addons:
  postgresql: "9.6"

services:
  - postgresql

cache:
  pip: true

before_install:
  - cd perma-payments

install:
  - pip install -U pip wheel
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  # linting
  - flake8 .

script:
  - fab test

after_success:
  - coverage report
  - coveralls
